
#############################################################
###        Private Validator Configuration Options        ###
#############################################################

[privval]

# The chain the validator validates for.
chain_id = ""
